version: '3.8'

services:
  heic-converter:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: heic-to-jpeg-converter
    ports:
      - "3000:3000"
    volumes:
      - ./input:/app/input
      - ./output:/app/output
      - temp_uploads:/tmp/uploads
      - temp_converted:/tmp/converted
    environment:
      - INPUT_DIR=/app/input
      - OUTPUT_DIR=/app/output
      - JPEG_QUALITY=85
      - PORT=3000
      - NODE_ENV=production
      - JWT_SECRET=your-production-jwt-secret-change-this
      - API_KEYS=secure-api-key-1,secure-api-key-2
      - ADMIN_PASSWORD_HASH=$$2b$$10$$example.hash.change.this
      - ALLOWED_ORIGINS=http://localhost:3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4545/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - heic-network

  # Versión CLI para conversiones por lotes
  heic-converter-cli:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: heic-converter-cli
    volumes:
      - ./input:/app/input
      - ./output:/app/output
    environment:
      - INPUT_DIR=/app/input
      - OUTPUT_DIR=/app/output
      - JPEG_QUALITY=90
      - NODE_ENV=production
    command: ["node", "converter.js"]
    profiles:
      - cli
    networks:
      - heic-network

volumes:
  temp_uploads:
  temp_converted:

networks:
  heic-network:
    driver: bridge